spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: my-retail-products-api

application:
  redsky:
    url: https://redsky-uat.perf.target.com
    apiKey: 3yUxt7WltYG7MFKPp7uyELi1K40ad2ys

server:
  error:
    include-message: ALWAYS